export enum AccountType {
  MAIN = "MAIN",
  SUB = "SUB",
}

export enum TransactionType {
  DEPOSIT = "DEPOSIT",
  SWAP = "SWAP",
  FIAT_DEPOSIT = "FIAT_DEPOSIT",
  WITHDRAW = "WITHDRAW",
  TRANSFER_IN = "TRANSFER_IN",
  TRANSFER_OUT = "TRANSFER_OUT",
  REALIZED_PNL = "REALIZED_PNL",
  FUNDING_FEE = "FUNDING_FEE",
  DEPOSIT_COPY_FUND = "DEPOSIT_COPY_FUND",
  WITHDRAW_COPY_FUND = "WITHDRAW_COPY_FUND",
  COMMISSION_FEE = "COMMISSION_FEE",
  LIQUIDATION_CLEARANCE = "LIQUIDATION_CLEARANCE",
  REFERRAL_KICKBACK = "REFERRAL_KICKBACK",
}

export enum TransactionStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  DONE = "DONE",
  FAILED = "FAILED",
}

export enum InternalTaskType {
  DEPOSIT = "DEPOSIT",
  UNLOCK = "UNLOCK",
  WITHDRAW = "WITHDRAW",
  CHECK_AND_LOCK = "CHECK_AND_LOCK",
  WITHDRAW_CONFIRMED = "WITHDRAW_CONFIRMED",
  SEND_NOTIFICATION = "SEND_NOTIFICATION",
  SEND_EMAIL = "SEND_EMAIL",
  UPDATE_COPY_MASTERS = "UPDATE_COPY_MASTERS",
  UPDATE_FOLLOW_ACCOUNTS = "UPDATE_FOLLOW_ACCOUNTS",
}

export enum InternalTaskStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  DONE = "DONE",
  FAILED = "FAILED",
}

export enum OrderTriggerDirection {
  UP = "UP",
  DOWN = "DOWN",
}

export enum OrderTriggerBy {
  MARK = "MARK",
  LAST = "LAST",
  INDEX = "INDEX",
}

export enum OrderSide {
  BUY = "BUY",
  SELL = "SELL",
}

export enum OrderType {
  LIMIT = "LIMIT",
  MARKET = "MARKET",
}

export enum OrderStatus {
  NEW = "NEW",
  PARTIALLY_FILLED = "PARTIALLY_FILLED",
  UN_TRIGGERED = "UN_TRIGGERED",
  REJECTED = "REJECTED",
  PARTIALLY_FILLED_CANCELED = "PARTIALLY_FILLED_CANCELED",
  FILLED = "FILLED",
  CANCELED = "CANCELED",
  TRIGGERED = "TRIGGERED",
  DEACTIVATED = "DEACTIVATED",
}

export enum TimeInForce {
  GTC = "GTC",
  IOC = "IOC",
  FOK = "FOK",
}

export enum TemplateType {
  VERIFICATION_EMAIL = "VERIFICATION_EMAIL",
  VERIFICATION_SMS = "VERIFICATION_SMS",
  EMAIL_VERIFICATION_CONFIRMATION = "EMAIL_VERIFICATION_CONFIRMATION",
  MOBILE_VERIFICATION_CONFIRMATION = "MOBILE_VERIFICATION_CONFIRMATION",
  NEW_INQUIRY = "NEW_INQUIRY",
  MIGRATE_PASSWORD_EMAIL = "MIGRATE_PASSWORD_EMAIL",
  MIGRATE_PASSWORD_SMS = "MIGRATE_PASSWORD_SMS",
}
